# 用于music和22个body joints的retrieval配置文件path
largedance:
    NAME: largedance_mb
    audio_dir: '/data2/hzy/InfiniteDance/InfiniteDanceData/music/musicfeature_55_allmusic_pure'
    mofea264_dir: '/data2/hzy/InfiniteDance/InfiniteDanceData/dance/alldata_new_joint_vecs264'
    meta_paths: '/data2/hzy/InfiniteDance/InfiniteDanceData/partition/alldata_mbr_s150_l600.json'
    # meta_paths: '/data2/hzy/InfiniteDance/InfiniteDanceData/partition/alldata_mbr_s100_l384.json'
    split: train

largedance_test:
    NAME: largedance_mb
    audio_dir: '/data2/hzy/InfiniteDance/InfiniteDanceData/music/musicfeature_55_allmusic_pure'
    mofea264_dir: '/data2/hzy/InfiniteDance/InfiniteDanceData/dance/alldata_new_joint_vecs264'
    # meta_paths: '/data2/hzy/InfiniteDance/InfiniteDanceData/partition/alldata_mbr_s100_l384.json'
    meta_paths: '/data2/hzy/InfiniteDance/InfiniteDanceData/partition/alldata_mbr_s150_l600.json'
    split: test

largedance_all:
    NAME: largedance_mb
    audio_dir: '/data2/hzy/InfiniteDance/InfiniteDanceData/music/musicfeature_55_allmusic_pure'
    mofea264_dir: '/data2/hzy/InfiniteDance/InfiniteDanceData/dance/alldata_new_joint_vecs264'
    meta_paths: '/data2/hzy/InfiniteDance/InfiniteDanceData/partition/alldata_mbr_s150_l600.json'
    split: all